//
// Created by Maikel on 26-12-2019.
//

#ifndef GBA_SPRITE_ENGINE_PROJECT_ENTITYMANAGER_H
#define GBA_SPRITE_ENGINE_PROJECT_ENTITYMANAGER_H


class EntityManager {

};


#endif //GBA_SPRITE_ENGINE_PROJECT_ENTITYMANAGER_H
